### ISSUE TITLE
Could you update to the latest SDK?

### ISSUE THREAD

**Issue by BillSobel** [alexdresko/HomeSeerNuget#1]
Hi.  The package is bit out of data with the latest HS changes (such as new enum values in ePairControlUse of _ColorControl)  Do you have plans to update the package to the latest?

**Comment by alexdresko** [comment]
Hi @BillSobel. I certainly can. If you want to save me a little time, attach the updated assemblies here and I'll push an updated package immediately. You can also create a PR and I'll happily approve it.

**Comment by BillSobel** [comment]
Hi, not setup on this machine do the PR (traveling today) but do have access to the binaries and am attaching them.  Thank you for responding so quickly!!  Zipping them up as the system won't allow .dll files.
[HSupdate.zip](https://github.com/alexdresko/HomeSeerNuget/files/2177514/HSupdate.zip)

**Comment by alexdresko** [comment]
Well, it only took forever, but I finally updated the nuget package.



Alex Dresko

Learn more at www.alexdresko.com<http://www.alexdresko.com>

________________________________

**Comment by BillSobel** [comment]
Thank you!
